import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/Components/Navbar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "My App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="max-w-7xl mx-auto p-4">
          <Navbar></Navbar>
          <div className="min-h-screen text-center font-bold text-3xl py-6">
            {children}
          </div>
          <footer>
            <h6 className="text-center">&copy; Nayemur 2025</h6>
          </footer>
        </div>
      </body>
    </html>
  );
}
